/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Client / Patient Portal (light theme)
        primary: '#006574',
        'primary-container': '#008092',
        'on-primary': '#ffffff',
        'on-primary-container': '#f8fdff',
        'primary-fixed': '#a3eeff',
        'primary-fixed-dim': '#63d6ec',
        'on-primary-fixed': '#001f25',
        'on-primary-fixed-variant': '#004e5a',
        secondary: '#516161',
        'secondary-container': '#d4e6e5',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#576867',
        'secondary-fixed': '#d4e6e5',
        'secondary-fixed-dim': '#b8cac9',
        'on-secondary-fixed': '#0e1e1e',
        'on-secondary-fixed-variant': '#3a4a49',
        tertiary: '#545c72',
        'tertiary-container': '#6c748b',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fefcff',
        'tertiary-fixed': '#dae2fd',
        'tertiary-fixed-dim': '#bec6e0',
        'on-tertiary-fixed': '#131b2e',
        'on-tertiary-fixed-variant': '#3f465c',
        surface: '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-variant': '#e0e3e5',
        'surface-tint': '#006877',
        'on-surface': '#191c1e',
        'on-surface-variant': '#3d494b',
        background: '#f7f9fb',
        'on-background': '#191c1e',
        outline: '#6d797c',
        'outline-variant': '#bcc9cc',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#63d6ec',
        // Admin Portal (dark theme overrides — applied via .dark class)
        'admin-bg': '#051424',
        'admin-surface': '#051424',
        'admin-surface-container': '#122131',
        'admin-surface-container-high': '#1c2b3c',
        'admin-surface-container-highest': '#273647',
        'admin-primary': '#c3f5ff',
        'admin-primary-container': '#00e5ff',
        'admin-on-primary': '#00363d',
        'admin-on-background': '#d4e4fa',
        'admin-on-surface': '#d4e4fa',
        'admin-on-surface-variant': '#bac9cc',
        'admin-outline-variant': '#3b494c',
        'admin-secondary-container': '#00626e',
        'admin-on-secondary-container': '#c3f5ff',
        'clinical-teal': '#00E5FF',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'data-numeric': ['14px', { lineHeight: '1.0', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        xxl: '64px',
        gutter: '24px',
        'container-max': '1280px',
      },
      boxShadow: {
        clinical: '0px 4px 12px rgba(15, 23, 42, 0.05)',
        'clinical-lg': '0px 12px 32px rgba(15, 23, 42, 0.1)',
        'clinical-xl': '0px 20px 48px rgba(15, 23, 42, 0.15)',
        'admin-glow': '0 0 20px rgba(0, 229, 255, 0.15)',
      },
      animation: {
        'fade-in': 'fadeIn 0.4s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-slow': 'bounceSlow 3s ease-in-out infinite',
        'shimmer': 'shimmer 1.5s ease-in-out infinite',
        'spin-slow': 'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(-12px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        bounceSlow: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [],
}
